-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gelu_top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    i_stream_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    i_stream_V_empty_n : IN STD_LOGIC;
    i_stream_V_read : OUT STD_LOGIC;
    o_stream_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    o_stream_V_full_n : IN STD_LOGIC;
    o_stream_V_write : OUT STD_LOGIC;
    scalars : IN STD_LOGIC_VECTOR (31 downto 0);
    table_r : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of gelu_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "gelu_top_gelu_top,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu5ev-sfvc784-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.752000,HLS_SYN_LAT=9510,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=48,HLS_SYN_LUT=148,HLS_VERSION=2020_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal gelu_inst_table_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_do_gelu_fu_40_ap_start : STD_LOGIC;
    signal grp_do_gelu_fu_40_ap_done : STD_LOGIC;
    signal grp_do_gelu_fu_40_ap_idle : STD_LOGIC;
    signal grp_do_gelu_fu_40_ap_ready : STD_LOGIC;
    signal grp_do_gelu_fu_40_i_stream_V_read : STD_LOGIC;
    signal grp_do_gelu_fu_40_o_stream_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_do_gelu_fu_40_o_stream_V_write : STD_LOGIC;
    signal grp_do_gelu_fu_40_this_table_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_do_gelu_fu_40_this_table_ce0 : STD_LOGIC;
    signal grp_do_gelu_fu_40_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component gelu_top_do_gelu IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        i_stream_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        i_stream_V_empty_n : IN STD_LOGIC;
        i_stream_V_read : OUT STD_LOGIC;
        o_stream_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        o_stream_V_full_n : IN STD_LOGIC;
        o_stream_V_write : OUT STD_LOGIC;
        this_table_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        this_table_ce0 : OUT STD_LOGIC;
        this_table_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component gelu_top_gelu_inst_table IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    gelu_inst_table_U : component gelu_top_gelu_inst_table
    generic map (
        DataWidth => 8,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_do_gelu_fu_40_this_table_address0,
        ce0 => grp_do_gelu_fu_40_this_table_ce0,
        q0 => gelu_inst_table_q0);

    grp_do_gelu_fu_40 : component gelu_top_do_gelu
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_do_gelu_fu_40_ap_start,
        ap_done => grp_do_gelu_fu_40_ap_done,
        ap_idle => grp_do_gelu_fu_40_ap_idle,
        ap_ready => grp_do_gelu_fu_40_ap_ready,
        i_stream_V_dout => i_stream_V_dout,
        i_stream_V_empty_n => i_stream_V_empty_n,
        i_stream_V_read => grp_do_gelu_fu_40_i_stream_V_read,
        o_stream_V_din => grp_do_gelu_fu_40_o_stream_V_din,
        o_stream_V_full_n => o_stream_V_full_n,
        o_stream_V_write => grp_do_gelu_fu_40_o_stream_V_write,
        this_table_address0 => grp_do_gelu_fu_40_this_table_address0,
        this_table_ce0 => grp_do_gelu_fu_40_this_table_ce0,
        this_table_q0 => gelu_inst_table_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_do_gelu_fu_40_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_do_gelu_fu_40_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_do_gelu_fu_40_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_do_gelu_fu_40_ap_ready = ap_const_logic_1)) then 
                    grp_do_gelu_fu_40_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_do_gelu_fu_40_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_do_gelu_fu_40_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_done_assign_proc : process(grp_do_gelu_fu_40_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_do_gelu_fu_40_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_do_gelu_fu_40_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_do_gelu_fu_40_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_do_gelu_fu_40_ap_start <= grp_do_gelu_fu_40_ap_start_reg;

    i_stream_V_read_assign_proc : process(grp_do_gelu_fu_40_i_stream_V_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            i_stream_V_read <= grp_do_gelu_fu_40_i_stream_V_read;
        else 
            i_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;

    o_stream_V_din <= grp_do_gelu_fu_40_o_stream_V_din;

    o_stream_V_write_assign_proc : process(grp_do_gelu_fu_40_o_stream_V_write, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            o_stream_V_write <= grp_do_gelu_fu_40_o_stream_V_write;
        else 
            o_stream_V_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
